sap:
  link:
    cats: "https://user-pets.cfapps.eu10.hana.ondemand.com/api/v1/cats"
    dogs: "https://user-pets.cfapps.eu10.hana.ondemand.com/api/v1/dogs"
    users: "https://user-pets.cfapps.eu10.hana.ondemand.com/api/v1/users"